apiVersion: apps/v1
kind: Deployment
metadata:
  name: db2-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db2-operator
  template:
    metadata:
      labels:
        name: db2-operator
    spec:
      serviceAccountName: db2-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: "10.44.91.21:5000/db2-operator:latest"
          imagePullPolicy: 'Always'
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: "10.44.91.21:5000/db2-operator:latest"
          imagePullPolicy: 'Always'
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "db2-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
