kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: db2-operator
subjects:
- kind: ServiceAccount
  name: db2-operator
  namespace: prabhat
roleRef:
  kind: ClusterRole
  name: db2-operator
  apiGroup: rbac.authorization.k8s.io
